### ISSUE TITLE
indexname with date pattern

### ISSUE THREAD

**Issue by thaarbach** [rfoltyns/log4j2-elasticsearch#1]
@rfoltyns is there any way to use a date pattern as part of the index name?
I tried `'log4j2-'yyyy-MM-dd` but this doesn't work. No index will be created. 
If this is missing, it would be great if you can implement that.

**Comment by rfoltyns** [comment]
Sure, I'll add it before the end of next week.

**Comment by rfoltyns** [comment]
@thaarbach I took a stab at this. Please have a look whether it will satisfy your needs or not.

I don't want to release new version just yet, cause I have a gut feeling that index template impl will introduce more changes in the API. It should be released next week though.
