### ISSUE TITLE
High number of "I/O dispatcher" threads using log4j2-elasticsearch-jest

### ISSUE THREAD

**Issue by JeromeSoussens** [rfoltyns/log4j2-elasticsearch#13]
log4j2-elasticsearch-jest can create a high number of "I/O dispatcher" threads. Actually, it creates one "I/O dispatcher" thread per available processor. Depending on the host machine, the thread count can be very high per JVM.

This seems to be caused by the httpcore-nio library (org.apache.httpcomponents:httpcore-nio version 4.4.4) : 
in IOReactorConfig, line 66 :
```
this.ioThreadCount = AVAIL_PROCS;
```
Then the threads are created in AbstractMultiworkerIOReactor, line 324 :
```
for (int i = 0; i < this.workerCount; i++) {
                final BaseIOReactor dispatcher = this.dispatchers[i];
                this.workers[i] = new Worker(dispatcher, eventDispatch);
                this.threads[i] = this.threadFactory.newThread(this.workers[i]);
}
```
Is there a workaround to avoid that  and creates only 1 or 2 threads ?

Thanks !

**Comment by rfoltyns** [comment]
@JeromeSoussens Good point!
The only workaround atm is to extend `JestHttpObjectFactory`(log4j2-elasticsearch-jest), `JestClientFactory`(jest) and `HttpClientConfig`(jest).

`IOReactorConfig.setIOThreadCount(int)` allows to configure it and set it at `AbstractMultiworkerIOReactor:157`, so I'll just expose it via `ioThreadCount` attribute at `JestHttp` and `JestBufferedHttp` in 1.3.1 (I'm planning on releasing it soon).

Great find! Thank you! 👍

**Comment by JeromeSoussens** [comment]
Hi @rfoltyns ,
Thanks for your reply, that would be great to be able to configure the ioThreadCount !

**Comment by JeromeSoussens** [comment]
Hi @rfoltyns ,
What are your plans regarding the fix for this issue ? Will it be in the next release ?

Thanks

**Comment by rfoltyns** [comment]
@JeromeSoussens I had to shift the priorities a bit due to more and more issues related with Spring Boot startup. I had to patch it asap.
I''ve planned to work on `ioThreadCount` this week though.. along with the extension of lifecycle integration to JestHttpClient. Hoping to fix another Spring Boot "quirk" - even though `ioThreadCount` is, e.g.: 8, actual number of IO threads is 16 cause the client starts twice!
Lifecycle extension and `ioThreadCount` config **WILL** be released in 1.3.2 (first half of February)

**Comment by rfoltyns** [comment]
Released in 1.3.2
Enjoy! :)

**Comment by JeromeSoussens** [comment]
Thank you very much !
It works like a charm.

**Comment by rfoltyns** [comment]
Glad to help! Thanks again for this.
If you have any other suggestions regarding useful config options, feel free to open more issues or PRs.

BTW, I've found that shrinking IO threads too low can choke the client easily on higher workloads, so use with caution ;)
