### ISSUE TITLE
Additional fields for logs

### ISSUE THREAD

**Issue by badabunta** [rfoltyns/log4j2-elasticsearch#20]
Hi. I'm using your library for streaming logs from Spring application directly to Elasticsearch. 
But i'm facing with problem that i don't understand how to add extra fields. 
My log4j2.xml config looks like:
```xml
<Elasticsearch name="elasticsearchAsyncBatch">
            <IndexName indexName="log4j2test" />
            <JacksonJsonLayout afterburner="true">
                <PooledItemSourceFactory itemSizeInBytes="1024" initialPoolSize="4000" />
            </JacksonJsonLayout>
            <AsyncBatchDelivery>
                <IndexTemplate name="log4j2test" path="classpath:indexTemplate.json" />
                <JestBufferedHttp serverUris="http://localhost:9200">
                    <PooledItemSourceFactory itemSizeInBytes="1024000" initialPoolSize="4" />
                </JestBufferedHttp>
            </AsyncBatchDelivery>
        </Elasticsearch>
```

Logs in Elasticsearch looks like:

`timeMillis:1,559,135,125,693 loggerName: com.test..api.UserController level:ERROR message:TEST  thread:http-nio-3201-exec-6 _id:GJkSVL8MFE2REW _type:index _index:log4j2test _score:0`

I want add for example: X-B3-ParentSpanId, X-B3-SpanId, X-B3-TraceId. 

BTW, my Elasticsearch is 7.0.1 v.
Any help is appreciated.

**Comment by rfoltyns** [comment]
@badabunta Passing additional properties is possible via Log4j2 ThreadContext. Please have a look at point 2. in [this comment](https://github.com/rfoltyns/log4j2-elasticsearch/issues/18#issuecomment-488107973).
As an alternative, you can use `<Elasticsearch messageOnly=true>` and [custom MessageFactory](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-core#raw-log-message) to produce any output that you want. It will not be pooled (unless you write it on your own), but I'm thinking about adding `PooledMessageFactory` if possible in future releases (probably >=1.5).
