### ISSUE TITLE
Supporting Filter

### ISSUE THREAD

**Issue by thaarbach** [rfoltyns/log4j2-elasticsearch#3]
Hi Rafal,
i tried to combine the ElasticsearchAppender with a ThresholdFilter, but i see that Filters are not supported.
Is it possible to support Filters?
Need something like that
```
		<Elasticsearch name="elasticsearch">
			<JsonLayout compact="true" properties="true" />
			<ThresholdFilter level="INFO" onMatch="ACCEPT"/>
			<AsyncBatchDelivery indexName="log4j2" deliveryInterval="5000" batchSize="500">
				<JestHttp serverUris="http://localhost:9200" />
			</AsyncBatchDelivery>
		</Elasticsearch>
```

**Comment by rfoltyns** [comment]
You're right, there's no support for Filters ATM. But it should be pretty straightforward to add. I'll have a look at it today. It looks like a pretty useful feature.

**Comment by thaarbach** [comment]
Hi,
i tried to implement it, but it's tricky to test it, because the Appender is wrapped by AppenderControl. Should submit a pull request?

**Comment by rfoltyns** [comment]
Sure, please do.

**Comment by rfoltyns** [comment]
@thaarbach I've applied minor changes to your commit (see [PR](https://github.com/rfoltyns/log4j2-elasticsearch/pull/4)) Thank you for this! :)
