### ISSUE TITLE
Mistyped ElasticsearchAppender#layout field causing plugin injection errors

### ISSUE THREAD

**Issue by vy** [rfoltyns/log4j2-elasticsearch#33]
`ElasticsearchAppender.Builder#layout` is of type `AbstractLayout`, whereas it should have been `Layout`. See Log4j 2.0 `FileAppender` for an example. This renders `ElasticsearchAppender` unusable for layouts that don't extend from `AbstractLayout`. For instance,  `LogstashLayout` doesn't extend from `AbstractLayout` class, but implements `Layout<String>` interface, hence the Log4j field injection failure reported in #32.

**Comment by rfoltyns** [comment]
I don't believe that the parameter is "mistyped". It's much easier to relax the interface than tighten one in the future (it started from `JsonLayout` btw).

But, to improve compatibility with other layouts, I'll relax it in 1.4.

**Comment by rfoltyns** [comment]
Fixed in 1.4.
