### ISSUE TITLE
Custom rolling index separator

### ISSUE THREAD

**Issue by cuneytcalishkan** [rfoltyns/log4j2-elasticsearch#37]
Hello,
Currently the rolling index separator is hard coded as the hyphen "-" character.
It would be nice to have it also configurable to a custom character e.g. dot.

What do you think about adding this improvement?

Best regards,
Cuneyt

**Comment by cuneytcalishkan** [comment]
I have created a PR for this feature, please see PR https://github.com/rfoltyns/log4j2-elasticsearch/pull/38

**Comment by rfoltyns** [comment]
I like the idea 👍 PR looks good. I've requested some minor changes. I'll merge it as soon as they are addressed.

Thank you for the contribution! :)

**Comment by cuneytcalishkan** [comment]
I have created a new PR with minimal changes and took into account your remarks. Please see PR #39
