### ISSUE TITLE
VirtualProperty to retrieve value associated to a key of MapMessage

### ISSUE THREAD

**Issue by benjamin-cartereau** [rfoltyns/log4j2-elasticsearch#46]
**Description**
I have a MapMessage in which I have a key named "packageName". I would like this key/value be mapped as a field.
I am trying to use VirtualProperty to retrieve the associated value through : $${map:packageName} (or even ${map:packageName}) but I cannot make it work.
I am ending up with "${map:packageName}" value in ES.
Is there a way to make VirtualProperty work with MapMessage?

N.B., with for eg. RollingRandomAccessFile I can use "%map{packageName}" in the pattern of the layout.

**Configuration**
Configuration used to produce the behavior: XML

```
<Elasticsearch name="elasticsearchAsyncBatch">
        <IndexName indexName="log4j2" />
	<JacksonJsonLayout afterburner="true">
              <VirtualProperty name="hostname" value="$${env:hostname:-undefined}" />
	      <VirtualProperty name="packageName" value="$${map:packageName}" dynamic="true" />
	      <PooledItemSourceFactory poolName="itemPool" itemSizeInBytes="1024" initialPoolSize="3000" />
        </JacksonJsonLayout>
        <AsyncBatchDelivery batchSize="1000" deliveryInterval="10000" >
		<IndexTemplate name="template_log4j2" path="classpath:indexTemplate-2.json" />
		<HCHttp serverUris="${elasticsearch-url}" mappingType="log">
                    <PooledItemSourceFactory poolName="batchPool" itemSizeInBytes="1024000" initialPoolSize="3" />
                </HCHttp>
         </AsyncBatchDelivery>
</Elasticsearch>
```

**Runtime :**
 - Module name and version: log4j2-elasticsearch-hc-1.4.1, log4j2-elasticsearch-core-1.4.1, log4j-core-2.12.1.jar
 - Framework/server/module system used : exotic (webMethods IS) / ES 5
 - JVM : Hotspot 1.8.0_101 (52.0)
 - OS: RHEL
 
**Additional context**
None

**Comment by rfoltyns** [comment]
I'm afraid that `MapMessage` won't work as you expect here. `MapMessage` lookup not supported by `VirtualProperty`. This is due t the fact that the property writer has no access to LogEvent.message at the time of `${map:packageName}` resolution.

It works for pattern-based layouts, because the the whole LogEvent with MapMessage is passed to resolver.

Would ThreadContext and `$${ctx:packageName}` be an acceptable alternative?

**Comment by benjamin-cartereau** [comment]
Thank you very much for your anwser.
Indeed, using the ThreadContext could be an acceptable alternative since I am starting from scratch and I can more easily switch.

I am also wondering if using mixins could be an answer.
Couldn't it be possible to have a custom serializer like the one specified in MessageJacksonJsonMixIn.
It would differ from JacksonJsonMessageSerializer (calling getFormattedMessage()) by calling getFormattedMessage(["JSON"]) (https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/message/MultiformatMessage.html#getFormattedMessage-java.lang.String:A-) if the message is an instance of MultiformatMessage (MapMessage).
This way, I would maybe get all entries of the Map as nested fields...

**Comment by rfoltyns** [comment]
Yes, custom serializer for `MultiformatMessage` would also do the trick. There won't be any need for dynamic replacement.

In case of ThreadContext, `VirtualProperty` will work with synchronous loggers.

If you'd like to use asynchronous loggers, you'll need mixins again to override ignores on context data. Look at some examples [here](https://github.com/rfoltyns/log4j2-elasticsearch/issues/18#issuecomment-488107973).

**Comment by benjamin-cartereau** [comment]
Thank you very much  for this clarification.
