### ISSUE TITLE
How to pass the value from ThreadContext to ValueProperty?

### ISSUE THREAD

**Issue by vaomaohaoone** [rfoltyns/log4j2-elasticsearch#58]
Hi!
I tried passing value from ThreadContext to VirtualProperty like this:

my code in Application:
`
        ThreadContext.put("account", "elvisPresley");
        Logger logger = LogManager.getLogger("elasticsearch");
        logger.info("HELLO");
`

section with ValueProperty in log4j2.xml: 
`<JacksonJsonLayout>
                <VirtualProperty name="name" value="$${ctx:account:-undefined}" />
</JacksonJsonLayout>
`

And I keep getting 'undefined' in Kibana fot my field.
Does anyone know how to solve this?
It is my mistake or a bug?

**Comment by vaomaohaoone** [comment]
I think, that a problem with threads (main thread and AsyncLogger thread are different :) )

**Comment by rfoltyns** [comment]
Yes, you're right - with `AsyncLogger` log serialization is happening on Log4j2 `AsyncLoggerConfig` thread, not the logging thread.

The difference in context data handling with `Logger` and `AsyncLogger` is that the values are not accessible via `ctx` lookup.

However, context data is still copied to `AsyncLogger`'s RingBufferLogEvent and MutableLogEvent and resolved on the fly, so you can serialize it with your own, custom serializer for context data as described in [this comment](https://github.com/rfoltyns/log4j2-elasticsearch/issues/18#issuecomment-488107973)

I hope it helps.

**Comment by vaomaohaoone** [comment]
Thanks!
