### ISSUE TITLE
Run elastic search appender in specific environment

### ISSUE THREAD

**Issue by viratbiz** [rfoltyns/log4j2-elasticsearch#86]
I am trying to run the elastic search appender in log4j2.xml only in production environment. Is there any way to do this?

**Comment by rfoltyns** [comment]
The most convenient way to do this is to configure it programmatically and enable it with a config flag.

Other than that, you can use Log4j2 Markers and log levels per environment to prevent logs from reaching the appender.

**Comment by rfoltyns** [comment]
@viratbiz Is there anything more I can address in the scope of this issue?
