### ISSUE TITLE
The issue with VirtualProperties and LogEventJacksonJsonMixIn

### ISSUE THREAD

**Issue by suxuanning** [rfoltyns/log4j2-elasticsearch#99]
![image](https://github.com/user-attachments/assets/1635d822-5ea2-4aa6-a803-643f88059657)
What is the difference between these two categories? The class that was not deprecated did not add 'virtualiProperties', resulting in the output not containing the values from' virtualiProperties'

` 
@JsonAppend(
    props = {@Prop(
    name = "virtualProperties",
    type = VirtualProperty.class,
    value = VirtualPropertiesWriter.class
)}
)
`

**my xml**
![image](https://github.com/user-attachments/assets/86ba87f3-6826-4cb1-b5d0-d9f5475f5e04)

my CustomLogEventMixIn
![image](https://github.com/user-attachments/assets/c2bd367b-e3b6-4ab3-af64-b86670eb0c2d)

**result**
![image](https://github.com/user-attachments/assets/c3c9923b-1735-4b50-bfd7-0b08a0b67b6d)

If I use deprecated classes, the result will output correctly
![image](https://github.com/user-attachments/assets/9277dde0-1514-4568-bddd-c470dfd3c0f2)

**result**
![image](https://github.com/user-attachments/assets/9675b83f-711e-4e9c-b39a-a58379b9cdb0)

My English is not very good, and the translation software I use may not have expressed it correctly.
I feel like this is a bug. The classes that were not deprecated should have lost the JsonAppend tag

**Comment by rfoltyns** [comment]
> The class that was not deprecated did not add 'virtualiProperties'

The extending class (and the class that is actually used in [`ExtendedLog4j2JsonModule`](https://github.com/rfoltyns/log4j2-elasticsearch/blob/master/log4j2-elasticsearch-core/src/main/java/org/appenders/log4j2/elasticsearch/thirdparty/LogEventJacksonJsonMixIn.java) did and should work just fine: [`ExtendedLogEventJacksonJsonMixIn`](https://github.com/rfoltyns/log4j2-elasticsearch/blob/master/log4j2-elasticsearch-core/src/main/java/org/appenders/log4j2/elasticsearch/json/jackson/ExtendedLog4j2JsonModule.java).

The reason behind leaving the deprecated ones there is mainly backwards compatibility within major version (currently 1.x) - I don't want to force users that extended it to migrate before 2.x

The reason behind deprecating it in the first place is the `Package naming conventions` issue - OSGi doesn't like Log4j2 packages popping up in non-Log4j2 jars. Users were forced to implement workarounds, so relevant classes had to be copied to `json.thirdparty`.

**Comment by rfoltyns** [comment]
> The classes that were not deprecated should have lost the JsonAppend tag

Removing `@JsonAppend` would stop the `VirtualProperty` from working at all, wouldn't it?

**Comment by suxuanning** [comment]
> > The classes that were not deprecated should have lost the JsonAppend tag
> 
> Removing `@JsonAppend` would stop the `VirtualProperty` from working at all, wouldn't it?

Yes, thank you for your clarification. Now, because I need to use `VirtualProperty`, I manually added `@JsonAppend` to the custom class.
